In [2]:
# Write numpy program to get the numpy versiion and show numpy build configuration

import numpy as np

# get numpy version
print("Numpy Version:", np.__version__)

# show Numpy build configuration
print("\nNumpy Build Configuration:", np.show_config())

Numpy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    s

In [4]:
# Write a Numpy program to get help on the add function.

# get help on the numpy add function
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [9]:
# Write a numpy program to test whether none of the elements of a given array is zero.

arr=np.array([1,2,3,4,5])
k=np.all(arr)
print("None of the elements is zero:", k)

None of the elements is zero: True


In [10]:
# Write a NumPy program to test whether any of the elements of a given array is non-zero.

arr=np.array([0,0,0,3,0])
r=np.any(arr)
print("Any of the elements is non-zero:", r)

Any of the elements is non-zero: True


In [11]:
# Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

arr=np.array([1, 0, np.inf, -np.inf, np.nan, 5])
r=np.isfinite(arr)
print("Finiteness check:", r)

Finiteness check: [ True  True False False False  True]


In [12]:
# Write a NumPy program to test element-wise for positive or negative infinity.

arr = np.array([1, np.inf, -np.inf, 0, 5, np.nan])
r=np.isinf(arr)
print(r)

[False  True  True False False False]


In [13]:
# Write a NumPy program to test element-wise for NaN of a given array.

arr = np.array([1, np.nan, 3, np.inf, -np.inf, np.nan, 5])
result = np.isnan(arr)
print(result)

[False  True False False False  True False]


In [14]:
# Write a NumPy program to test element-wise for complex number, real number of a given array.
# Also test whether a given number is a scalar type or not.

arr = np.array([1, 2+3j, 5.5, 0, -1j])
c=np.iscomplex(arr)
r=np.isreal(arr)
scalar=5
scalar2=np.array([5])
i=np.isscalar(scalar)
j=np.isscalar(scalar2)
print("Original Array:", arr)
print("Complex check", c)
print("real check:", r)
print("scalar", scalar)
print("isscalar", scalar2)

Original Array: [ 1. +0.j  2. +3.j  5.5+0.j  0. +0.j -0. -1.j]
Complex check [False  True False False  True]
real check: [ True False  True  True False]
scalar 5
isscalar [5]


In [15]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

arr1=np.array([1,4,7,10])
arr2=np.array([3,4,6,10])

g=np.greater(arr1, arr2)
ge=np.greater_equal(arr1, arr2)
l=np.less(arr1,arr2)
le=np.less_equal(arr1,arr2)
print(g)
print(ge)
print(l)
print(le)

[False False  True False]
[False  True  True  True]
[ True False False False]
[ True  True False  True]


In [16]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

arr = np.array([1,7,13,105])
memory_size = arr.nbytes
print("Array:", arr)
print("Memory size occupied by the array in bytes:", memory_size)

Array: [  1   7  13 105]
Memory size occupied by the array in bytes: 16


In [17]:
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

zeros=np.zeros(10)
ones=np.ones(10)
fives_array=np.full(10,5)
print(zeros)
print(ones)
print(fives_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [18]:
# Write a NumPy program to create an array of the integers from 30 to70.

k=np.arange(30,71)
print(k)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [19]:
# Write a NumPy program to create an array of all the even integers from 30 to 70.

arr=np.arange(30,71, 2)
print("Array of even integers from 30 to 70:", arr)


Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [21]:
# Write a NumPy program to create a 3x3 identity matrix.

identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# Write a NumPy program to generate a random number between 0 and 1.
random_number = np.random.rand()
print("Random number between 0 and 1:", random_number)

Random number between 0 and 1: 0.6720376507320556


In [23]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

random_array = np.random.rand(15)
print("Array of 15 random numbers from a standard normal distribution:")
print(random_array)



Array of 15 random numbers from a standard normal distribution:
[0.80561831 0.55085793 0.66388799 0.06583462 0.54238497 0.98962433
 0.50269263 0.01500292 0.04577814 0.27311222 0.23657651 0.79477845
 0.5586948  0.08953335 0.19647018]


In [24]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

vector = np.arange(15, 56)
k=vector[1:-1]
print("Vector with values except the first and last:", result)

Vector with values except the first and last: [False  True False False False  True False]


In [29]:
# Write a NumPy program to create a 3X4 array using and iterate over it.
k=np.random.randint(1, 10, (3,4))

print("3x4 Array:")
print('\n')
print(k)
print('\n')
print("\n Iterating over the array :")
for i in k:
    print(i)

3x4 Array:


[[5 4 4 5]
 [4 7 7 5]
 [7 8 8 6]]



 Iterating over the array :
[5 4 4 5]
[4 7 7 5]
[7 8 8 6]


In [32]:
# Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

vector = np.linspace(5, 50, 10)
print("Vector with values evenly distributed between 5 and 50:")
print(vector)

Vector with values evenly distributed between 5 and 50:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

vector = np.arange(21)
vector[9:16] = -vector[9:16]
print("Modified Vector")
print(vector)

In [33]:
# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

vector = np.random.randint(0, 11, size=5)
print("Random vector of length 5 (values from 0 to 10):")
print(vector)

Random vector of length 5 (values from 0 to 10):
[7 2 0 1 9]


In [34]:
# Write a NumPy program to multiply the values of two given vectors.

vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([10, 20, 30, 40, 50])

r=np.multiply(vector1, vector2)
print(r)


[ 10  40  90 160 250]


In [37]:
# Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

a=np.arange(10,22)
m=a.reshape(3,4)
print("3x4 matrix with values from 10 to 21:")
print(m)

print('\n')
for k in m:
    print(k)

3x4 matrix with values from 10 to 21:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


[10 11 12 13]
[14 15 16 17]
[18 19 20 21]


In [39]:
# Write a NumPy program to find the number of rows and columns of a given matrix.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

rows, columns = matrix.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 4
Number of columns: 3


In [40]:
# Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
