Write a Pandas program to create and display a one-dimensional array-like
object containing an array of data using Pandas module.

In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.Series([2,4,6,8,10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


2. Write a Pandas program to convert a Panda module Series to Python list
and it's type.

In [3]:
ds=pd.Series([2,4,6,8,10])
print("Pandas Series And Type:")
print(ds)
print(type(ds))
print('\n')
print("Convert Pandas Series to Python List :")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series And Type:
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>


Convert Pandas Series to Python List :
[2, 4, 6, 8, 10]
<class 'list'>


3. Write a Pandas program to add, subtract, multiple and divide two Pandas
Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [4]:
ds1=pd.Series([2,4,6,8,10])
ds2=pd.Series([1,3,5,7,9])
print("Add two Series:")
ds=ds1+ds2
print(ds)
print('\n')
print("Substract two Series:")
ds=ds1-ds2
print(ds)
print('\n')
print("Multipy two Series:")
ds=ds*ds2
print(ds)
print('\n')

print("Divide Series by Series2:")
ds=ds1/ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64


Substract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64


Multipy two Series:
0    1
1    3
2    5
3    7
4    9
dtype: int64


Divide Series by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4. Write a Pandas program to compare the elements of the two Pandas
Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [5]:
ds1=pd.Series([2,4,6,8,10])
ds2=pd.Series([1,3,5,7,10])
print("Series1:")
print(ds1)
print('\n')
print("Series2")
print(ds2)
print("\n")
print("Compare the elements of the said Series:")
print("\n")
print("Equals")
print(ds1==ds2)
print('\n')
print('Greater Than:')
print(ds1>ds2)
print("\n")
print(ds1<ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64


Series2
0     1
1     3
2     5
3     7
4    10
dtype: int64


Compare the elements of the said Series:


Equals
0    False
1    False
2    False
3    False
4     True
dtype: bool


Greater Than:
0     True
1     True
2     True
3     True
4    False
dtype: bool


0    False
1    False
2    False
3    False
4    False
dtype: bool


5. Write a Pandas program to convert a dictionary to a Pandas series.
Sample Series:
- Original dictionary:
- {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
- Converted series:
- a 100
- b 200
- c 300
- d 400
- e 800
- dtype: int64

In [6]:
d1={'a':100, 'b':200, 'c':300, 'd':400, 'e':800}
print("Original Dictionary:")
print(d1)
print('\n')
new_series = pd.Series(d1)
print("Converted Series:")
print(new_series)

Original Dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}


Converted Series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


6. Write a Pandas program to convert a NumPy array to a Pandas series.
- Sample Series:
- NumPy array:
- [10 20 30 40 50]
- Converted Pandas series:
- 0 10
- 1 20
- 2 30
- 3 40
- 4 50
- dtype: int64

In [7]:
np_array=np.array([10,20,30,40,50])
print("Numpy Array:")
print(np_array)
print('\n')
new_series = pd.Series(np_array)
print("Converted Pandas Series:")
print(new_series)

Numpy Array:
[10 20 30 40 50]


Converted Pandas Series:
0    10
1    20
2    30
3    40
4    50
dtype: int32


7. Write a Pandas program to change the data type of given a column or a
Series.
- Sample Series:
- Original Data Series:
- 0 100

- 1 200
- 2 python
- 3 300.12
- 4 400
- dtype: object
- Change the said data type to numeric:
- 0 100.00
- 1 200.00
- 2 NaN
- 3 300.12
- 4 400.00
- dtype: float64

In [8]:
s1=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric :")
s2=pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Change the said data type to numeric :
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


- 8. Write a Pandas program to convert the first column of a DataFrame as a
- Series.
- Sample Output:
- Original DataFrame
- col1 col2 col3
- 0 1 4 7
- 1 2 5 5
- 2 3 6 8
- 3 4 9 12
- 4 7 5 1
- 5 11 0 11
- 1st column as a Series:
- 0 1
- 1 2
- 2 3
- 3 4
- 4 7
- 5 11
- Name: col1, dtype: int64
- <class 'pandas.core.series.Series'>

In [9]:
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}
df=pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
print("\n")
s1=df.iloc[:,0]
print('\n1st column as a series:')
print(s1)
print(type(s1))

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11



1st column as a series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


9. Write a Pandas program to convert a given Series to an array.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array

In [11]:
s1=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series")
print(s1)
print('\n')
print("Series to an array")
a=s1.values
print(a)
print(type(a))

Original Data Series
0       100
1       200
2    python
3    300.12
4       400
dtype: object


Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>


10. Write a Pandas program to convert Series of lists to one Series.
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow

In [12]:
s=pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])
print("Original Series of list")
print(s)
s=s.apply(pd.Series).stack().reset_index(drop=True)
print("one Series")
print(s)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
one Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


11. Write a Pandas program to sort a given Series.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object

In [14]:
s=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\n")
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
3    300.12
4       400
2    python
dtype: object


12. Write a Pandas program to add some data to an existing Series.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
5 500

6 php
dtype: object

In [16]:
s=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series")
print(s)
print("\n Data Series after adding some data:")
new_s = pd.concat([s, pd.Series([500, 'php'])], ignore_index=True)
print(new_s)

Original Data Series
0       100
1       200
2    python
3    300.12
4       400
dtype: object

 Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object


13. Write a Pandas program to create a subset of a given series based on value and
condition.
Sample Output:
Original Data Series:
0 0
1 1
2 2
....
9 9
10 10
dtype: int64
Subset of the above Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
dtype: int64

In [17]:
s=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print('Original Data Seriess:')
print(s)
print("\n Subset of the above Data Series:")
n=6
new_s = s[s<n]
print(new_s)

Original Data Seriess:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

 Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


14. Write a Pandas program to change the order of index of a given series.
Sample Output:
Original Data Series:
A 1
B 2
C 3
D 4
E 5
dtype: int64
Data Series after changing the order of index:
B 2
A 1
C 3
D 4
E 5
dtype: int64

In [18]:
s=pd.Series(data=[1,2,3,4,5], index=['A', 'B', 'C', 'D', 'E'])
print("Original Data Series:")
print(s)
print("\n")
s=s.reindex(index=['B', 'A', 'C', 'D', 'E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64


Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


15. Write a Pandas program to create the mean and standard deviation of the data of a
given Series.
Sample Output:
Original Data Series:
0 1
1 2
2 3

....
7 8
8 9
9 5
10 3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565

In [20]:
s=pd.Series(data=[1,2,3,4,5,6,7,8,5,3])
print("Original Data Series:")
print(s)
print("\n")
print("Mean of the said Data Series:")
print(s.mean())
print("\n")
print("Standard Deviation of the said Data Series:")
print(s.std())


Original Data Series:
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    5
9    3
dtype: int64


Mean of the said Data Series:
4.4


Standard Deviation of the said Data Series:
2.2211108331943574


16. Write a Pandas program to get the items of a given series not present in another given
series.
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of sr1 not present in sr2:
0 1
2 3
4 5
dtype: int64

In [21]:
sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])
print("Original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\nItems of sr1 not present in sr2")
result=sr1[~sr1.isin(sr2)]
print(result)

Original Series:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2
0    1
2    3
4    5
dtype: int64


17. Write a Pandas program to get the items which are not common of two given series.
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10

dtype: int64
Items of a given series not present in another given series:
0 1
2 3
4 5
5 6
6 8
7 10
dtype: int64

In [22]:
sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])
print("Original Series :")
print("sr1 :")
print(sr1)
print("sr2 :")
print(sr2)
print("\n Items of a give series not present in another given Series:")
sr11=pd.Series(np.union1d(sr1, sr2))
sr22=pd.Series(np.intersect1d(sr1,sr2))
result=sr11[~sr11.isin(sr22)]
print(result)

Original Series :
sr1 :
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2 :
0     2
1     4
2     6
3     8
4    10
dtype: int64

 Items of a give series not present in another given Series:
0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64


18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and
maximum of a given series.
Sample Output:
Original Series:
0 3.000938
1 11.370722
2 14.612143
....
17 14.118931
18 8.247458
19 5.526727
dtype: float64
Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]

In [23]:
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10,4,20))
print("Original Series:")
print(num_series)
result = np.percentile(num_series, q=[0,25,50,75,100])
print("\nMinimum, 25th percentile, median , 75th and maximum of a given Series:")
print(result)

Original Series:
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

Minimum, 25th percentile, median , 75th and maximum of a given Series:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


19. Write a Pandas program to calculate the frequency counts of each unique value of a
given series.
Sample Output:
Original Series:
0 1
1 7
2 1
3 6
...

37 0
38 4
39 8
dtype: object
Frequency of each unique value of the said series.
0 9
2 7
9 6
....
3 2
4 1
5 1

In [24]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))
print("Original Series:")
print(num_series)
print("Frequency of each unique value of the said series.")
result = num_series.value_counts()
print(result)


Original Series:
0     5
1     0
2     2
3     6
4     7
5     3
6     8
7     6
8     2
9     7
10    7
11    0
12    3
13    9
14    1
15    3
16    6
17    3
18    5
19    7
20    7
21    6
22    7
23    1
24    2
25    6
26    6
27    9
28    6
29    2
30    9
31    3
32    6
33    6
34    6
35    6
36    5
37    9
38    7
39    3
dtype: object
Frequency of each unique value of the said series.
6    11
7     7
3     6
2     4
9     4
5     3
0     2
1     2
8     1
Name: count, dtype: int64


20. Write a Pandas program to display most frequent value in a given series and replace
everything else as 'Other' in the series.
Sample Output:
Original Series:
0 3
1 1
2 1
3 3
...
12 2
13 3
14 3
dtype: int64
Top 2 Freq: 2 6
3 5
1 4
dtype: int64
0 Other
1 Other
2 Other
3 Other
...
11 2
12 2
13 Other
14 Other
dtype: object

In [25]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1, 5, [15]))
print("Original Series:")
print(num_series)
print("Top 2 Freq:", num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)


Original Series:
0     3
1     3
2     1
3     2
4     3
5     2
6     3
7     4
8     4
9     4
10    3
11    1
12    2
13    1
14    4
dtype: int32
Top 2 Freq: 3    5
4    4
1    3
2    3
Name: count, dtype: int64
0         3
1         3
2     Other
3     Other
4         3
5     Other
6         3
7     Other
8     Other
9     Other
10        3
11    Other
12    Other
13    Other
14    Other
dtype: object
