Write a Pandas program to create and display a one-dimensional array-like
object containing an array of data using Pandas module.

In [38]:
import pandas as pd
import numpy as np

In [39]:
ds=pd.Series([2,4,6,8,10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


2. Write a Pandas program to convert a Panda module Series to Python list
and it's type.

In [40]:
ds=pd.Series([2,4,6,8,10])
print("Pandas Series And Type:")
print(ds)
print(type(ds))
print('\n')
print("Convert Pandas Series to Python List :")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series And Type:
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>


Convert Pandas Series to Python List :
[2, 4, 6, 8, 10]
<class 'list'>


3. Write a Pandas program to add, subtract, multiple and divide two Pandas
Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [41]:
ds1=pd.Series([2,4,6,8,10])
ds2=pd.Series([1,3,5,7,9])
print("Add two Series:")
ds=ds1+ds2
print(ds)
print('\n')
print("Substract two Series:")
ds=ds1-ds2
print(ds)
print('\n')
print("Multipy two Series:")
ds=ds*ds2
print(ds)
print('\n')

print("Divide Series by Series2:")
ds=ds1/ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64


Substract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64


Multipy two Series:
0    1
1    3
2    5
3    7
4    9
dtype: int64


Divide Series by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4. Write a Pandas program to compare the elements of the two Pandas
Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [42]:
ds1=pd.Series([2,4,6,8,10])
ds2=pd.Series([1,3,5,7,10])
print("Series1:")
print(ds1)
print('\n')
print("Series2")
print(ds2)
print("\n")
print("Compare the elements of the said Series:")
print("\n")
print("Equals")
print(ds1==ds2)
print('\n')
print('Greater Than:')
print(ds1>ds2)
print("\n")
print(ds1<ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64


Series2
0     1
1     3
2     5
3     7
4    10
dtype: int64


Compare the elements of the said Series:


Equals
0    False
1    False
2    False
3    False
4     True
dtype: bool


Greater Than:
0     True
1     True
2     True
3     True
4    False
dtype: bool


0    False
1    False
2    False
3    False
4    False
dtype: bool


5. Write a Pandas program to convert a dictionary to a Pandas series.
Sample Series:
- Original dictionary:
- {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
- Converted series:
- a 100
- b 200
- c 300
- d 400
- e 800
- dtype: int64

In [43]:
d1={'a':100, 'b':200, 'c':300, 'd':400, 'e':800}
print("Original Dictionary:")
print(d1)
print('\n')
new_series = pd.Series(d1)
print("Converted Series:")
print(new_series)

Original Dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}


Converted Series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


6. Write a Pandas program to convert a NumPy array to a Pandas series.
- Sample Series:
- NumPy array:
- [10 20 30 40 50]
- Converted Pandas series:
- 0 10
- 1 20
- 2 30
- 3 40
- 4 50
- dtype: int64

In [44]:
np_array=np.array([10,20,30,40,50])
print("Numpy Array:")
print(np_array)
print('\n')
new_series = pd.Series(np_array)
print("Converted Pandas Series:")
print(new_series)

Numpy Array:
[10 20 30 40 50]


Converted Pandas Series:
0    10
1    20
2    30
3    40
4    50
dtype: int32


7. Write a Pandas program to change the data type of given a column or a
Series.
- Sample Series:
- Original Data Series:
- 0 100

- 1 200
- 2 python
- 3 300.12
- 4 400
- dtype: object
- Change the said data type to numeric:
- 0 100.00
- 1 200.00
- 2 NaN
- 3 300.12
- 4 400.00
- dtype: float64

In [45]:
s1=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric :")
s2=pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Change the said data type to numeric :
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


- 8. Write a Pandas program to convert the first column of a DataFrame as a
- Series.
- Sample Output:
- Original DataFrame
- col1 col2 col3
- 0 1 4 7
- 1 2 5 5
- 2 3 6 8
- 3 4 9 12
- 4 7 5 1
- 5 11 0 11
- 1st column as a Series:
- 0 1
- 1 2
- 2 3
- 3 4
- 4 7
- 5 11
- Name: col1, dtype: int64
- <class 'pandas.core.series.Series'>

In [46]:
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}
df=pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
print("\n")
s1=df.iloc[:,0]
print('\n1st column as a series:')
print(s1)
print(type(s1))

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11



1st column as a series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


9. Write a Pandas program to convert a given Series to an array.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array

In [47]:
s1=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series")
print(s1)
print('\n')
print("Series to an array")
a=s1.values
print(a)
print(type(a))

Original Data Series
0       100
1       200
2    python
3    300.12
4       400
dtype: object


Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>


10. Write a Pandas program to convert Series of lists to one Series.
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow

In [48]:
s=pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])
print("Original Series of list")
print(s)
s=s.apply(pd.Series).stack().reset_index(drop=True)
print("one Series")
print(s)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object


one Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


11. Write a Pandas program to sort a given Series.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object

In [49]:
s=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\n")
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
3    300.12
4       400
2    python
dtype: object


12. Write a Pandas program to add some data to an existing Series.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
5 500

6 php
dtype: object

In [50]:
s=pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series")
print(s)
print("\n Data Series after adding some data:")
new_s = pd.concat([s, pd.Series([500, 'php'])], ignore_index=True)
print(new_s)

Original Data Series
0       100
1       200
2    python
3    300.12
4       400
dtype: object

 Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object


13. Write a Pandas program to create a subset of a given series based on value and
condition.
Sample Output:
Original Data Series:
0 0
1 1
2 2
....
9 9
10 10
dtype: int64
Subset of the above Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
dtype: int64

In [51]:
s=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print('Original Data Seriess:')
print(s)
print("\n Subset of the above Data Series:")
n=6
new_s = s[s<n]
print(new_s)

Original Data Seriess:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

 Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


14. Write a Pandas program to change the order of index of a given series.
Sample Output:
Original Data Series:
A 1
B 2
C 3
D 4
E 5
dtype: int64
Data Series after changing the order of index:
B 2
A 1
C 3
D 4
E 5
dtype: int64

In [52]:
s=pd.Series(data=[1,2,3,4,5], index=['A', 'B', 'C', 'D', 'E'])
print("Original Data Series:")
print(s)
print("\n")
s=s.reindex(index=['B', 'A', 'C', 'D', 'E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64


Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


15. Write a Pandas program to create the mean and standard deviation of the data of a
given Series.
Sample Output:
Original Data Series:
0 1
1 2
2 3

....
7 8
8 9
9 5
10 3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565

In [53]:
s=pd.Series(data=[1,2,3,4,5,6,7,8,5,3])
print("Original Data Series:")
print(s)
print("\n")
print("Mean of the said Data Series:")
print(s.mean())
print("\n")
print("Standard Deviation of the said Data Series:")
print(s.std())


Original Data Series:
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    5
9    3
dtype: int64


Mean of the said Data Series:
4.4


Standard Deviation of the said Data Series:
2.2211108331943574


16. Write a Pandas program to get the items of a given series not present in another given
series.
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of sr1 not present in sr2:
0 1
2 3
4 5
dtype: int64

In [54]:
sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])
print("Original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\nItems of sr1 not present in sr2")
result=sr1[~sr1.isin(sr2)]
print(result)

Original Series:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2
0    1
2    3
4    5
dtype: int64


17. Write a Pandas program to get the items which are not common of two given series.
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10

dtype: int64
Items of a given series not present in another given series:
0 1
2 3
4 5
5 6
6 8
7 10
dtype: int64

In [55]:
sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])
print("Original Series :")
print("sr1 :")
print(sr1)
print("sr2 :")
print(sr2)
print("\n Items of a give series not present in another given Series:")
sr11=pd.Series(np.union1d(sr1, sr2))
sr22=pd.Series(np.intersect1d(sr1,sr2))
result=sr11[~sr11.isin(sr22)]
print(result)

Original Series :
sr1 :
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2 :
0     2
1     4
2     6
3     8
4    10
dtype: int64

 Items of a give series not present in another given Series:
0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64


18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and
maximum of a given series.
Sample Output:
Original Series:
0 3.000938
1 11.370722
2 14.612143
....
17 14.118931
18 8.247458
19 5.526727
dtype: float64
Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]

In [56]:
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10,4,20))
print("Original Series:")
print(num_series)
result = np.percentile(num_series, q=[0,25,50,75,100])
print("\nMinimum, 25th percentile, median , 75th and maximum of a given Series:")
print(result)

Original Series:
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

Minimum, 25th percentile, median , 75th and maximum of a given Series:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


19. Write a Pandas program to calculate the frequency counts of each unique value of a
given series.
Sample Output:
Original Series:
0 1
1 7
2 1
3 6
...

37 0
38 4
39 8
dtype: object
Frequency of each unique value of the said series.
0 9
2 7
9 6
....
3 2
4 1
5 1

In [57]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))
print("Original Series:")
print(num_series)
print("Frequency of each unique value of the said series.")
result = num_series.value_counts()
print(result)


Original Series:
0     9
1     8
2     5
3     7
4     3
5     7
6     0
7     4
8     9
9     0
10    4
11    6
12    0
13    0
14    1
15    3
16    4
17    1
18    9
19    3
20    2
21    3
22    0
23    1
24    9
25    7
26    2
27    0
28    5
29    6
30    6
31    8
32    5
33    7
34    9
35    7
36    1
37    4
38    1
39    1
dtype: object
Frequency of each unique value of the said series.
0    6
1    6
9    5
7    5
3    4
4    4
5    3
6    3
8    2
2    2
Name: count, dtype: int64


20. Write a Pandas program to display most frequent value in a given series and replace
everything else as 'Other' in the series.
Sample Output:
Original Series:
0 3
1 1
2 1
3 3
...
12 2
13 3
14 3
dtype: int64
Top 2 Freq: 2 6
3 5
1 4
dtype: int64
0 Other
1 Other
2 Other
3 Other
...
11 2
12 2
13 Other
14 Other
dtype: object

In [58]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1, 5, [15]))
print("Original Series:")
print(num_series)
print("Top 2 Freq:", num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)


Original Series:
0     3
1     1
2     3
3     4
4     4
5     3
6     2
7     2
8     3
9     3
10    3
11    3
12    1
13    1
14    4
dtype: int32
Top 2 Freq: 3    7
1    3
4    3
2    2
Name: count, dtype: int64
0         3
1     Other
2         3
3     Other
4     Other
5         3
6     Other
7     Other
8         3
9         3
10        3
11        3
12    Other
13    Other
14    Other
dtype: object


21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a
given series.
Sample Output:
Original Series:
0 1
1 9
2 8
3 6
4 9
5 7
6 1
7 1
8 1
dtype: int64

In [59]:
num_series = pd.Series(np.random.randint(1, 10, 9))
print("Original Series:")
print(num_series)
result = np.where(num_series%5==0)
print("Positions of numbers that are multiples of 5:")
print(result)

Original Series:
0    1
1    4
2    8
3    8
4    8
5    1
6    6
7    1
8    9
dtype: int32
Positions of numbers that are multiples of 5:
(array([], dtype=int64),)


22. Write a Pandas program to extract items at given positions of a given series.
Sample Output:
Original Series:
0 2
1 3
2 9
3 0
4 2
5 3
...
19 0
20 2
21 3
dtype: object
Extract items at given positions of the said series:
0 2
2 9
6 8
11 0
21 3
dtype: object

In [60]:
num_series = pd.Series(list('2390238923902390239023'))
element_pos = [0,2,6,11,21]
print("Original Series:")
print(num_series)
result=num_series.take(element_pos)
print("\Extract items at given positions of the said series:")
print(result)

Original Series:
0     2
1     3
2     9
3     0
4     2
5     3
6     8
7     9
8     2
9     3
10    9
11    0
12    2
13    3
14    9
15    0
16    2
17    3
18    9
19    0
20    2
21    3
dtype: object
\Extract items at given positions of the said series:
0     2
2     9
6     8
11    0
21    3
dtype: object


<>:6: SyntaxWarning: invalid escape sequence '\E'
<>:6: SyntaxWarning: invalid escape sequence '\E'
C:\Users\Asus\AppData\Local\Temp\ipykernel_13640\3522767750.py:6: SyntaxWarning: invalid escape sequence '\E'
  print("\Extract items at given positions of the said series:")


23. Write a Pandas program to get the positions of items of a given series in another
given series.
Sample Output:
Original Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
dtype: int64
0 1
1 3
2 5
3 7
4 10
dtype: int64
Positions of items of series2 in series1:
[0, 2, 4, 6, 9]

In [61]:
series1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
series2 = pd.Series([1,3,5,7,10])
print("Original Series:")
print(series1)
print(series2)
print('\n')
result = [pd.Index(series1).get_loc(i) for i in series2]
print("Position of items of series2 in series1:")
print(result)

Original Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0     1
1     3
2     5
3     7
4    10
dtype: int64


Position of items of series2 in series1:
[0, 2, 4, 6, 9]


24. Write a Pandas program convert the first and last character of each word to upper
case in each word of a given series.
Sample Output:
Original Series:
0 php
1 python
2 java
3 c#
dtype: object
First and last character of each word to upper case:
0 PhP
1 PythoN
2 JavA
3 C#
dtype: object

In [62]:
series1=pd.Series(['php', 'python', 'java', 'c#'])
print("Original Series:")
print(series1)
result = series1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
print("\nFirst and last character of each word to upper case:")
print(result)



Original Series:
0       php
1    python
2      java
3        c#
dtype: object

First and last character of each word to upper case:
0       PhP
1    PythoN
2      JavA
3        C#
dtype: object


25. Write a Pandas program to calculate the number of characters in each word in a given
series.
Sample Output:
Original Series:
0 Php
1 Python
2 Java
3 C#
dtype: object
Number of characters in each word in the said series:
0 3
1 6
2 4
3 2
dtype: int64

In [63]:
series1 = pd.Series(['Php', 'python', 'java', 'c#'])
print("Original Series:")
print(series1)
result = series1.map(lambda x:len(x))
print("\n NUmber of characters in each word in the said series:")
print(result)

Original Series:
0       Php
1    python
2      java
3        c#
dtype: object

 NUmber of characters in each word in the said series:
0    3
1    6
2    4
3    2
dtype: int64


26. Write a Pandas program to compute difference of differences between consecutive
numbers of a given series.
Sample Output:
Original Series:
0 1
1 3
2 5
3 8
4 10
5 11
6 15
dtype: int64
Difference of differences between consecutive numbers of the said series:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]

In [64]:
series1=pd.Series([1,3,5,8,10,11,15])
print("Original Series:")
print(series1)
print("\nDifference of differences between consecutive numbers of the said series:")
print(series1.diff().tolist())
print(series1.diff().diff().tolist())



Original Series:
0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64

Difference of differences between consecutive numbers of the said series:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


27. Write a Pandas program to convert a series of date strings to a timeseries.
Sample Output:
Original Series:
0 01 Jan 2015
1 10-02-2016
2 20180307
3 2014/05/06
4 2016-04-12
5 2019-04-06T11:20
dtype: object
Series of date strings to a timeseries:
0 2015-01-01 00:00:00
1 2016-10-02 00:00:00
2 2018-03-07 00:00:00
3 2014-05-06 00:00:00
4 2016-04-12 00:00:00
5 2019-04-06 11:20:00
dtype: datetime64[ns]

In [65]:
# date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
# print("Original Series:")
# print(date_series)
# print("\nSeries of date strings to a timeseries:")
# print(pd.to_datetime(date_series))

28. Write a Pandas program to get the day of month, day of year, week number and day
of week from a given series of date strings.
Sample Output:
Original Series:
0 01 Jan 2015
1 10-02-2016
2 20180307
3 2014/05/06
4 2016-04-12
5 2019-04-06T11:20
dtype: object
Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:
[1, 39, 10, 19, 15, 14]
Day of week:
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']

In [ ]:
# import pandas as pd
# from dateutil.parser import parse
# date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
# print("Original Series:")
# print(date_series)
# date_series = date_series.map(lambda x: parse(x))
# print("Day of month:")
# print(date_series.dt.day.tolist())
# print("Day of year:")
# print(date_series.dt.dayofyear.tolist())
# print("Week number:")
# print(date_series.dt.weekofyear.tolist())
# print("Day of week:")
# print(date_series.dt.weekday_name.tolist())


Original Series:
0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object
Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:


AttributeError: 'DatetimeProperties' object has no attribute 'weekofyear'

29. Write a Pandas program to convert year-month string to dates adding a specified day
of the month.
Sample Output:
Original Series:
0 Jan 2015
1 Feb 2016
2 Mar 2017
3 Apr 2018
4 May 2019

dtype: object
New dates:
0 2015-01-11
1 2016-02-11
2 2017-03-11
3 2018-04-11
4 2019-05-11
dtype: datetime64[ns]

In [67]:
import pandas as pd
from dateutil.parser import parse
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)


Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


30. Write a Pandas program to filter words from a given series that contain atleast two
vowels.
Sample Output:
Original Series:
0 Red
1 Green
2 Orange
3 Pink
4 Yellow
5 White
dtype: object
Filtered words:
1 Green
2 Orange
4 Yellow
5 White
dtype: object

In [68]:
import pandas as pd
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
print("Original Series:")
print(color_series)
print("\nFiltered words:")
result =color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(color_series[result])


Original Series:
0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object

Filtered words:
1     Green
2    Orange
4    Yellow
5     White
dtype: object


31. Write a Pandas program to compute the Euclidean distance between two given series.
Euclidean distance
From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line
distance between two points in Euclidean space. With this distance, Euclidean space
becomes a metric space. The associated norm is called the Euclidean norm.
Sample Output:
Original series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
dtype: int64
0 11

1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Euclidean distance between two said series:
16.492422502470642

In [69]:
import pandas as pd
import numpy as np
x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original series:")
print(x)
print(y)
print("\nEuclidean distance between two said series:")
print(np.linalg.norm(x-y))


Original series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0    11
1     8
2     7
3     5
4     6
5     5
6     3
7     4
8     7
9     1
dtype: int64

Euclidean distance between two said series:
16.492422502470642


32. Write a Pandas program to find the positions of the values neighboured by smaller
values on both sides in a given series.
Sample Output:
Original series:
0 1
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Positions of the values surrounded by smaller values on both sides:
[1 4 8]

In [70]:
import pandas as pd
import numpy as np
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original series:")
print(nums)
print("\nPositions of the values surrounded by smaller values on both sides:")
temp = np.diff(np.sign(np.diff(nums)))
result = np.where(temp == -2)[0] + 1
print(result)


Original series:
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

Positions of the values surrounded by smaller values on both sides:
[1 4 8]


33. Write a Pandas program to replace missing white spaces in a given string with the
least frequent character.
Sample Output:
Original series:
abc def abcdef icd
c 3
d 3
3
b 2
e 2
a 2
f 2
i 1
dtype: int64
abcidefiabcdefiicd