In [1]:
import numpy as np

In [2]:
# Basic Array Creation

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3], [4,5,6]])
arr3 = np.array((7,8,9))
print("Basic Array")
print(arr1)
print(arr2)
print(arr3)

print("1d:", arr1, "\n2d:", arr2, "\n3d:", arr3)

Basic Array
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[7 8 9]
1d: [1 2 3 4 5 6] 
2d: [[1 2 3]
 [4 5 6]] 
3d: [7 8 9]


In [3]:
# Special Array Creation

line = np.linspace(0, 10, 5)     # 5 Numbers from 0 to 10
print(line)

rang = np.arange(0, 1, 3)
print(rang)

[ 0.   2.5  5.   7.5 10. ]
[0]


In [4]:
# Special Array Creation

line = np.linspace(0, 20, 5)     # 5 Numbers from 0 to 10
print(line)

rang = np.arange(0, 30, 3)   
print(rang)

[ 0.  5. 10. 15. 20.]
[ 0  3  6  9 12 15 18 21 24 27]


In [6]:
rand_normal = np.random.randn(3, 3) # 3x3 Random Normal Distribution
print(rand_normal)

[[-1.40680866 -0.19877526  0.96166597]
 [ 1.53090322  0.24934693  0.25737614]
 [ 0.98948722  0.31105992  0.34734075]]


In [11]:
rand_custom_normal = np.random.normal(0,5, (3,3))
print(rand_custom_normal)

[[-1.40429668 -8.39845753  2.8767536 ]
 [ 0.33249893 -5.9540914  -7.95899566]
 [ 1.32621614 -4.02094773 -3.17197911]]


In [ ]:
lis = [1,2,3,2.0]
new_arr = np.array(lis) # Convert list to array
print(new_arr)          

[1. 2. 3. 2.]


In [13]:
r=np.arange(12)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
reshaped=np.arange(12).reshape(3,4) # Reshape array to 3x4
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
zero = np.zeros_like(reshaped) # Create array of zeros with same shape as reshaped
print(zero)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
ones = np.ones_like(reshaped) # Create array of ones with same shape as reshaped
print(ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
full = np.full_like(reshaped, 5) # Create array of fives with same shape as reshaped
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
reshaped = np.arange(12).reshape(3,4) # 3x4 matrix with numbers from 0 to 11
zero = np.zeros_like(reshaped) # 3x4 matrix with all elements 0
ones = np.ones_like(reshaped) # 3x4 matrix with all elements 1
full = np.full_like(reshaped, 5) # 3x4 matrix with all elements 5
print("zero:", zero, "\nones", ones, "\nfull", full,"\nreshaped:\n", reshaped)

zero: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 
ones [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 
full [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]] 
reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
arr_deep = arr.copy() # Create a deep copy of arr
print(arr_deep)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
arr[5] = 100 # Change the value of arr[5] to 100
print(arr)
print(arr_deep) # arr_deep remains unchanged

[  1   2   3   4   5 100   7   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
print(arr[arr>4])

[  5 100   7   8   9  10]


In [23]:
x = 5
print(arr[arr>x]) # Print elements of arr greater than x

[100   7   8   9  10]


In [26]:
a = np.arange(10)
print(a)
b = np.arange(10, 20)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(a%2) # Modulus operator
print(a//2) # Floor division operator
print(a**2) # Exponentiation operator
print(a**3) # Exponentiation operator

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]
[0 0 1 1 2 2 3 3 4 4]
[ 0  1  4  9 16 25 36 49 64 81]
[  0   1   8  27  64 125 216 343 512 729]


In [27]:
print(np.sqrt(a))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [28]:
print(np.log(a))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\Asus\AppData\Local\Temp\ipykernel_336\897204776.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [29]:
print(a.sum()) # Sum of all elements in a
print(a.max()) # Maximum element in a
print(a.min()) # Minimum element in a
print(a.mean()) # Mean of all elements in a
print(a.std()) # Standard deviation of all elements in a
print(a.var()) # Variance of all elements in a

45
9
0
4.5
2.8722813232690143
8.25


In [30]:
print(np.iinfo(np.int32)) # Information about int32 data type

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------



In [31]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
print(np.sort(a))

[0 1 2 3 4 5 6 7 8 9]
