In [1]:
import numpy as np
import pandas as pd

In [3]:
sales = [0,5,155,2,158, 0, 616]
sales_array = np.array(sales)
print(sales_array)

[  0   5 155   2 158   0 616]


In [4]:
print(type(sales_array))
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"Size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")

<class 'numpy.ndarray'>
ndim: 1
shape: (7,)
Size: 7
dtype: int32


Where And Filtering

# Where() function


In [5]:
result_array = np.where(sales_array ==0, "No Sales", "Sales")
print(result_array)

['No Sales' 'Sales' 'Sales' 'Sales' 'Sales' 'No Sales' 'Sales']


In [11]:
# Show all boolean values where condition is applied

bool_mask = sales_array!=0
print(bool_mask)

[False  True  True  True  True False  True]


In [12]:
# Filter Using Boolean mask

filtered_sales = sales_array[bool_mask]
print(filtered_sales)

[  5 155   2 158 616]


In [18]:
a = [5,6,7,"num", 45]
a_array = np.array(a)
print(a_array)
result_array1 = np.where(isinstance(int, float), "Number", "Not a Number")
print(result_array1)

# 


['5' '6' '7' 'num' '45']
Not a Number


In [19]:
a=[5, 6, 7, 'num', 45]
a_array = np.array(a)
print(a_array.dtype)

<U11


In [29]:
year = [2018, 2019, 2020, 2021, 2022]
year2 = [2025, 2026, 2027, 2028, 2029]
index_name = ["a", 'b', 'c', 'd', 'e']
year_sr = pd.Series(year, name = 'year')
print(year_sr)
year_sr2 = pd.Series(year2, name='Year2')
print(year_sr2)
df1 = pd.merge(year_sr, year_sr2, how='outer', left_index=True, right_index=True)
print(df1)

0    2018
1    2019
2    2020
3    2021
4    2022
Name: year, dtype: int64
0    2025
1    2026
2    2027
3    2028
4    2029
Name: Year2, dtype: int64
   year  Year2
0  2018   2025
1  2019   2026
2  2020   2027
3  2021   2028
4  2022   2029


In [30]:
print(df1.iloc[2])


year     2020
Year2    2027
Name: 2, dtype: int64


In [31]:
print(df1.loc[[0,2,4]])

   year  Year2
0  2018   2025
2  2020   2027
4  2022   2029


In [32]:
print(year_sr.keys())

RangeIndex(start=0, stop=5, step=1)


In [34]:
# Create a sample Series with missing values

data_method = pd.Series([1, np.nan, 3, np.nan, 5])
print("\nOriginal Series:\n", data_method)


Original Series:
 0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
dtype: float64


In [35]:
# Forward Fill
forward_filled = data_method.fillna(method='ffill')
print("\n Series after forwar fill: \n", forward_filled)


 Series after forwar fill: 
 0    1.0
1    1.0
2    3.0
3    3.0
4    5.0
dtype: float64


In [36]:
# Backward Fill
backward_filled = data_method.fillna(method='bfill')
print("\nSeries after backward fill:\n", backward_filled)


Series after backward fill:
 0    1.0
1    3.0
2    3.0
3    5.0
4    5.0
dtype: float64


In [41]:
np.random.seed(101)
mydata=np.random.randint(0, 101, (4, 3))
print(mydata)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [42]:
myindex = ['CA', 'NY', 'AZ', 'TX']
mycolumns = ['Jan', 'Feb', 'Mar']
print(myindex)
print(mycolumns)

['CA', 'NY', 'AZ', 'TX']
['Jan', 'Feb', 'Mar']


In [51]:
#  Create a DataFrame without index and columns
print(mydata)
print(myindex)
df = pd.DataFrame(data=mydata)
print(df)
df1 = pd.DataFrame(data=mydata, index = myindex)
print(df)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]
['CA', 'NY', 'AZ', 'TX']
    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63
    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63


In [52]:
# Create a DataFrame with custom index and columns

df=pd.DataFrame(data=mydata, index=myindex, columns=mycolumns)
print(df)
df.info()

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [53]:
print(df.columns)
print(df.index)
print(df.values)

Index(['Jan', 'Feb', 'Mar'], dtype='object')
Index(['CA', 'NY', 'AZ', 'TX'], dtype='object')
[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]
