Write a Numpy program to get the numpy version and show numpy build configuration.

In [1]:
import numpy as np

In [3]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


Write a NumPy program to get help on the add function.

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Write a NumPy program to test whether none of the elements of a given array is zero.

In [8]:
x=np.array([1,2,3,4])
print("Original Array:")
print(x)

print("Test if none of the elements of the said array is zero:")
print(np.all(x))

xy=np.array([0,1,2,3])
print("Original Array")
print(xy)

print("Test if none of the elements of the siad array is zero:")
print(np.all(xy))

Original Array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original Array
[0 1 2 3]
Test if none of the elements of the siad array is zero:
False


Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [10]:
x=np.array([1,0,0,0])
print("Original Array")
print(x)

print("Test Whether any of the elements of a given array is non-zero:")
print(np.any(x))

print("\n")

xy=np.array([0,0,0,0])
print("Original Array:")
print(xy)
print(" Test whether any of the elements of a give array is non zero:")
print(np.any(xy))

Original Array
[1 0 0 0]
Test Whether any of the elements of a given array is non-zero:
True


Original Array:
[0 0 0 0]
 Test whether any of the elements of a give array is non zero:
False


Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a
Number).

In [11]:
a=np.array([1,0,np.nan, np.inf])
print("Original Array:")
print(a)
print('\n')
print("Test a given array element wise for finiteness :")
print(np.isfinite(a))

Original Array:
[ 1.  0. nan inf]


Test a given array element wise for finiteness :
[ True  True False False]


In [14]:
array = np.array([1, -2, np.inf, -np.inf, 0, 3.5])
result_pos_inf = np.isposinf(array)
result_neg_inf = np.isneginf(array)

print("Elementwise positive infinity check :", result_pos_inf)
print("Elementwise negative infinity check:", result_neg_inf)

Elementwise positive infinity check : [False False  True False False False]
Elementwise negative infinity check: [False False False  True False False]


Write a NumPy program to test element-wise for NaN of a given array.