Write a Numpy program to get the numpy version and show numpy build configuration.

In [1]:
import numpy as np

In [3]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


Write a NumPy program to get help on the add function.

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Write a NumPy program to test whether none of the elements of a given array is zero.

In [8]:
x=np.array([1,2,3,4])
print("Original Array:")
print(x)

print("Test if none of the elements of the said array is zero:")
print(np.all(x))

xy=np.array([0,1,2,3])
print("Original Array")
print(xy)

print("Test if none of the elements of the siad array is zero:")
print(np.all(xy))

Original Array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original Array
[0 1 2 3]
Test if none of the elements of the siad array is zero:
False


Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [10]:
x=np.array([1,0,0,0])
print("Original Array")
print(x)

print("Test Whether any of the elements of a given array is non-zero:")
print(np.any(x))

print("\n")

xy=np.array([0,0,0,0])
print("Original Array:")
print(xy)
print(" Test whether any of the elements of a give array is non zero:")
print(np.any(xy))

Original Array
[1 0 0 0]
Test Whether any of the elements of a given array is non-zero:
True


Original Array:
[0 0 0 0]
 Test whether any of the elements of a give array is non zero:
False


Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a
Number).

In [11]:
a=np.array([1,0,np.nan, np.inf])
print("Original Array:")
print(a)
print('\n')
print("Test a given array element wise for finiteness :")
print(np.isfinite(a))

Original Array:
[ 1.  0. nan inf]


Test a given array element wise for finiteness :
[ True  True False False]


In [14]:
array = np.array([1, -2, np.inf, -np.inf, 0, 3.5])
result_pos_inf = np.isposinf(array)
result_neg_inf = np.isneginf(array)

print("Elementwise positive infinity check :", result_pos_inf)
print("Elementwise negative infinity check:", result_neg_inf)

Elementwise positive infinity check : [False False  True False False False]
Elementwise negative infinity check: [False False False  True False False]


Write a NumPy program to test element-wise for NaN of a given array.

In [15]:
a=np.array([1,0,np.nan, np.inf])
print("Original Array")
print(a)
print('\n')
print("Test Element wise for Nan:")
print(np.isnan(a))

Original Array
[ 1.  0. nan inf]


Test Element wise for Nan:
[False False  True False]


Write a NumPy program to test element-wise for complex number, real number of a given array.
Also test whether a given number is a scalar type or not.

In [16]:
a=np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original Array:")
print(a)
print('\n')
print("Checking for complex number:")
print(np.iscomplex(a))
print('\n')
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print('\n')
print(np.isscalar([3.1]))

Original Array:
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]


Checking for complex number:
[ True False False False False  True]


Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True


False


Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
less_equal) of two given arrays.

In [24]:
x=np.array([3,5])
y=np.array([2,5])
print("\n")
print("Original Numbers :")
print(x)
print(y)
print("\n")
print("Comparison - greater")
print(np.greater(x, y))
print("\n")
print("Comparison - greater_equal")
print(np.greater_equal(x,y))
print("\n")
print("Comparison - less")
print(np.less(x,y))
print('\n')
print("Comparison - less_equal")
print(np.less_equal(x,y))




Original Numbers :
[3 5]
[2 5]


Comparison - greater
[ True False]


Comparison - greater_equal
[ True  True]


Comparison - less
[False False]


Comparison - less_equal
[False  True]


Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of
the memory occupied by the array.

In [28]:
x=np.array([1,7,13,105])
print("Original Array:")
print(x)
print(x.size)
print(x.itemsize)
print("Size of the memeory occupied by the said array:")
print("%d bytes" % (x.size * x.itemsize))

Original Array:
[  1   7  13 105]
4
4
Size of the memeory occupied by the said array:
16 bytes


Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [30]:
array = np.zeros(10)
print("Any array of 10 zeros:")
print(array)
print("\n")
array=np.ones(10)
print("An array of 10 ones:")
print(array)
print('\n')
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)

Any array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of the integers from 30 to70.

In [31]:
array = np.arange(30, 71)
print("Array of the integers from 30 to 70")
print(array)

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Write a NumPy program to create an array of all the even integers from 30 to 70.

In [32]:
array = np.arange(30, 71, 2)
print("Array of the integers from 30 to 70")
print(array)

Array of the integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Write a NumPy program to create a 3x3 identity matrix.

In [33]:
array_2d = np.identity(3)
print('3x3 matrix:')
print(array_2d)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
array_2d = np.identity(5)
print('3x3 matrix:')
print(array_2d)

3x3 matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Write a NumPy program to generate a random number between 0 and 1.

In [37]:
rand_num = np.random.normal(0, 1, 1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[0.38190363]


In [38]:
rand_num = np.random.normal(0, 1, 3)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-1.59665862 -1.16109389  1.69418948]


Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.

In [39]:
rand_num = np.random.normal(0, 1, 15)
print("15 random numbers from a standard normal distribution :")
print(rand_num)

15 random numbers from a standard normal distribution :
[ 0.39802276 -0.43721524 -0.35494448  0.63749768 -0.10807239 -0.04855807
 -1.03692337 -0.34675744 -1.49196256  0.87852807  0.42072505  0.68881782
 -0.5743914  -0.56197732 -0.17176456]


Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.

In [40]:
v = np.arange(15, 55)
print("Original Vector :")
print(v)
print('\n')
print("All values except the first and last of the said vector")
print(v[1:-1])

Original Vector :
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


All values except the first and last of the said vector
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


Write a NumPy program to create a 3X4 array using and iterate over it.