Write a Numpy program to get the numpy version and show numpy build configuration.

In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


Write a NumPy program to get help on the add function.

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Write a NumPy program to test whether none of the elements of a given array is zero.

In [4]:
x=np.array([1,2,3,4])
print("Original Array:")
print(x)

print("Test if none of the elements of the said array is zero:")
print(np.all(x))

xy=np.array([0,1,2,3])
print("Original Array")
print(xy)

print("Test if none of the elements of the siad array is zero:")
print(np.all(xy))

Original Array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original Array
[0 1 2 3]
Test if none of the elements of the siad array is zero:
False


Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [5]:
x=np.array([1,0,0,0])
print("Original Array")
print(x)

print("Test Whether any of the elements of a given array is non-zero:")
print(np.any(x))

print("\n")

xy=np.array([0,0,0,0])
print("Original Array:")
print(xy)
print(" Test whether any of the elements of a give array is non zero:")
print(np.any(xy))

Original Array
[1 0 0 0]
Test Whether any of the elements of a given array is non-zero:
True


Original Array:
[0 0 0 0]
 Test whether any of the elements of a give array is non zero:
False


Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a
Number).

In [6]:
a=np.array([1,0,np.nan, np.inf])
print("Original Array:")
print(a)
print('\n')
print("Test a given array element wise for finiteness :")
print(np.isfinite(a))

Original Array:
[ 1.  0. nan inf]


Test a given array element wise for finiteness :
[ True  True False False]


In [7]:
array = np.array([1, -2, np.inf, -np.inf, 0, 3.5])
result_pos_inf = np.isposinf(array)
result_neg_inf = np.isneginf(array)

print("Elementwise positive infinity check :", result_pos_inf)
print("Elementwise negative infinity check:", result_neg_inf)

Elementwise positive infinity check : [False False  True False False False]
Elementwise negative infinity check: [False False False  True False False]


Write a NumPy program to test element-wise for NaN of a given array.

In [8]:
a=np.array([1,0,np.nan, np.inf])
print("Original Array")
print(a)
print('\n')
print("Test Element wise for Nan:")
print(np.isnan(a))

Original Array
[ 1.  0. nan inf]


Test Element wise for Nan:
[False False  True False]


Write a NumPy program to test element-wise for complex number, real number of a given array.
Also test whether a given number is a scalar type or not.

In [9]:
a=np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original Array:")
print(a)
print('\n')
print("Checking for complex number:")
print(np.iscomplex(a))
print('\n')
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print('\n')
print(np.isscalar([3.1]))

Original Array:
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]


Checking for complex number:
[ True False False False False  True]


Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True


False


Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
less_equal) of two given arrays.

In [10]:
x=np.array([3,5])
y=np.array([2,5])
print("\n")
print("Original Numbers :")
print(x)
print(y)
print("\n")
print("Comparison - greater")
print(np.greater(x, y))
print("\n")
print("Comparison - greater_equal")
print(np.greater_equal(x,y))
print("\n")
print("Comparison - less")
print(np.less(x,y))
print('\n')
print("Comparison - less_equal")
print(np.less_equal(x,y))




Original Numbers :
[3 5]
[2 5]


Comparison - greater
[ True False]


Comparison - greater_equal
[ True  True]


Comparison - less
[False False]


Comparison - less_equal
[False  True]


Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of
the memory occupied by the array.

In [11]:
x=np.array([1,7,13,105])
print("Original Array:")
print(x)
print(x.size)
print(x.itemsize)
print("Size of the memeory occupied by the said array:")
print("%d bytes" % (x.size * x.itemsize))

Original Array:
[  1   7  13 105]
4
4
Size of the memeory occupied by the said array:
16 bytes


Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [12]:
array = np.zeros(10)
print("Any array of 10 zeros:")
print(array)
print("\n")
array=np.ones(10)
print("An array of 10 ones:")
print(array)
print('\n')
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)

Any array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of the integers from 30 to70.

In [13]:
array = np.arange(30, 71)
print("Array of the integers from 30 to 70")
print(array)

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Write a NumPy program to create an array of all the even integers from 30 to 70.

In [14]:
array = np.arange(30, 71, 2)
print("Array of the integers from 30 to 70")
print(array)

Array of the integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Write a NumPy program to create a 3x3 identity matrix.

In [15]:
array_2d = np.identity(3)
print('3x3 matrix:')
print(array_2d)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
array_2d = np.identity(5)
print('3x3 matrix:')
print(array_2d)

3x3 matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Write a NumPy program to generate a random number between 0 and 1.

In [17]:
rand_num = np.random.normal(0, 1, 1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-1.14876847]


In [18]:
rand_num = np.random.normal(0, 1, 3)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[0.72357485 1.06643069 1.81573541]


Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.

In [19]:
rand_num = np.random.normal(0, 1, 15)
print("15 random numbers from a standard normal distribution :")
print(rand_num)

15 random numbers from a standard normal distribution :
[-1.69990751  0.21041813  1.24948331 -0.1995352  -0.99007624 -0.73086726
 -0.30343652  0.44732672  0.7845417   1.07757829  1.83652464  0.65995234
  0.0546666   0.52208713 -1.93002932]


Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.

In [20]:
v = np.arange(15, 55)
print("Original Vector :")
print(v)
print('\n')
print("All values except the first and last of the said vector")
print(v[1:-1])

Original Vector :
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


All values except the first and last of the said vector
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


Write a NumPy program to create a 3X4 array using and iterate over it.

In [26]:
a1=np.arange(10,22)
print("Original Array:")
print(a1)
print('\n')
print("Each Element of the array is:")
for x in np.nditer(a):
    print(x, end='')


Original Array:
[10 11 12 13 14 15 16 17 18 19 20 21]


Each Element of the array is:
101112131415161718192021

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5
and 50.

In [27]:
v=np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed betweenn 5 and 50:")
print(v)

Length 10 with values evenly distributed betweenn 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
numbers in the range from 9 to 15.

In [29]:
x=np.arange(21)
print("Original Vector:")
print(x)
print('\n')
x[(x>=9)&(x<=15)]*=-1
print("After changing the sign of the numbers in the range from 9 to 15:")
print(x)

Original Vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [33]:
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integgers from 0 to 10:")
print(x)

Vector of length 5 filled with arbitrary integgers from 0 to 10:
[ 0 10  3  1  1]


NumPy: Multiply the values ​​of two given vectors


In [37]:
x=np.array([1,8,3,5])
print('Vector-1')
print(x)
print('\n')
y=np.random.randint(0,11,4)
print('Vector-2')
print(y)
print('\n')
result = x*y
print("Multiply the values of two said vectors:")
print(result)

Vector-1
[1 8 3 5]


Vector-2
[ 5 10  4  7]


Multiply the values of two said vectors:
[ 5 80 12 35]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [40]:
m=np.arange(10,22).reshape((3,4))
print(m)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


Write a NumPy program to find the number of rows and columns of a given matrix.

In [42]:
m=np.arange(10,22).reshape((3,4))
print("NUmber of rows and columns of the said matrix:")
print(m.shape)

NUmber of rows and columns of the said matrix:
(3, 4)


Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [45]:
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
equal to 1, and inside 0.